[package]
name = "gbeed"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
paste = "1.0.15"

[dependencies.raylib]
git = "https://github.com/raylib-rs/raylib-rs"
version = "5.7.0"
