[package]
name = "gbeed-ui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gbeed"
path = "src/main.rs"

[dependencies]
gbeed-core = { path = "../core" }
raylib = { git = "https://github.com/raylib-rs/raylib-rs", version = "5.7.0" }
